// Generated by CoffeeScript 1.9.3
(function() {
  Object.prototype.delegate = function() {
    var args, delegation, i, len, method, methods, options, prefixedMethod, ref, results;
    args = Array.prototype.slice.call(arguments);
    ref = [args.slice(0, +(args.length - 2) + 1 || 9e9), args[args.length - 1]], methods = ref[0], options = ref[1];
    results = [];
    for (i = 0, len = methods.length; i < len; i++) {
      method = methods[i];
      delegation = function(method, delegatedMethod) {
        return this[method] = function() {
          var attribute, target;
          target = this[options.to];
          target = _.isFunction(target) ? target.apply(this) : target;
          attribute = target[delegatedMethod];
          if (_.isFunction(attribute)) {
            return attribute.apply(target, arguments);
          } else {
            return attribute;
          }
        };
      };
      if (options.prefix) {
        prefixedMethod = options.prefix + method.substr(0, 1).toUpperCase() + method.substr(1);
      }
      results.push(delegation.call(this.prototype, prefixedMethod || method, method));
    }
    return results;
  };

}).call(this);
