// Generated by CoffeeScript 1.3.3
(function() {

  describe("content binding", function() {
    return describe("#bindTo", function() {
      var element, model;
      element = $("<p></p>")[0];
      model = new Backbone.Model({
        name: "original name"
      });
      beforeEach(function() {
        return new Traction.Bindings.ContentBinding(element, "name").bindTo(model);
      });
      it("sets the content of element", function() {
        return expect(element.innerHTML).toBe("original name");
      });
      return it("updates the content of the element when the property changes", function() {
        model.set("name", "updated name");
        return expect(element.innerHTML).toBe("updated name");
      });
    });
  });

}).call(this);
