// Generated by CoffeeScript 1.8.0
(function() {
  jasmine.sharedExamplesFor("a text field", function(options) {
    describe("#render", function() {
      it("renders an input with the correct placeholder", function() {
        var field;
        field = options.createInstance().render();
        return expect(field.$(options.input).attr("placeholder")).toBe("First name");
      });
      return it("allows the placeholder to be specified", function() {
        var field;
        field = options.createInstance({
          placeholder: "alternative placeholder"
        }).render();
        return expect(field.$(options.input).attr("placeholder")).toBe("alternative placeholder");
      });
    });
    return describe("#clear", function() {
      return it("clears the input value", function() {
        var field;
        field = options.createInstance().render();
        field.set("ABC");
        field.clear();
        return expect(field.get()).toBe("");
      });
    });
  });

}).call(this);
