// Generated by CoffeeScript 1.3.3
(function() {

  Traction.Bindings.Binding = (function() {

    function Binding() {}

    Binding.prototype.bindTo = function(model) {
      this.model = model;
      this.model.on("change:" + this.property, this.update, this);
      return this.update();
    };

    return Binding;

  })();

}).call(this);
