// Generated by CoffeeScript 1.9.3
(function() {
  Traction.Bindings.Binding = (function() {
    function Binding() {}

    Binding.prototype.bindTo = function(model) {
      this.model = model;
      this.model.on("change:" + this.property, this.update, this);
      this.update();
      return this;
    };

    Binding.prototype.destroy = function() {
      return this.model.off(null, null, this);
    };

    return Binding;

  })();

}).call(this);
