// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Traction.Bindings.ContentBinding = (function(superClass) {
    extend(ContentBinding, superClass);

    function ContentBinding(el, specification) {
      this.el = el;
      this.specification = specification;
      this.property = this.specification;
    }

    ContentBinding.prototype.update = function(options) {
      return this.el.innerHTML = this.model.get(this.property) || "";
    };

    return ContentBinding;

  })(Traction.Bindings.Binding);

}).call(this);
