// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    slice = [].slice;

  Traction.Bindings.FormattedContentBinding = (function(superClass) {
    extend(FormattedContentBinding, superClass);

    function FormattedContentBinding(el, specification) {
      var ref;
      this.el = el;
      this.specification = specification;
      ref = this.specification.split("|"), this.property = ref[0], this.formatters = 2 <= ref.length ? slice.call(ref, 1) : [];
      this.formattingFunctions = _.map(this.formatters, (function(_this) {
        return function(formatter) {
          return _this._callFormattingFunction(formatter);
        };
      })(this));
    }

    FormattedContentBinding.prototype.update = function(options) {
      return this.el.innerHTML = _.reduce(this.formattingFunctions, (function(memo, formattingFunction) {
        return formattingFunction(memo);
      }), this.model.get(this.property));
    };

    FormattedContentBinding.prototype._callFormattingFunction = function(formatter) {
      var args, formattingFunction, ref;
      ref = this._extractArgs(formatter), formatter = ref[0], args = 2 <= ref.length ? slice.call(ref, 1) : [];
      if (formattingFunction = this._formatters()[formatter]) {
        return function(content) {
          return formattingFunction.apply(this, [content].concat(args));
        };
      } else {
        throw "Can't find formatter: " + formatter;
      }
    };

    FormattedContentBinding.prototype._extractArgs = function(formatter) {
      var reversed;
      reversed = _.str.reverse(formatter).split(/:(?!\\)/).reverse();
      return _.map(reversed, function(substring) {
        return _.str.reverse(substring).replace(/\\:/g, ':');
      });
    };

    FormattedContentBinding.prototype._formatters = function() {
      return _.extend(Traction.TemplateHelpers.Formatting, Traction.config.formatters);
    };

    return FormattedContentBinding;

  })(Traction.Bindings.Binding);

}).call(this);
