// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Traction.Forms.Field = (function(_super) {

    __extends(Field, _super);

    function Field() {
      return Field.__super__.constructor.apply(this, arguments);
    }

    Field.prototype.className = "field";

    Field.prototype.events = {
      "change input": "applyAutoCommit"
    };

    Field.prototype.initialize = function() {
      this.options = _.extend(this._defaults(), this.options);
      return this.listenTo(this.model, "change:" + this.options.attribute, this.reset);
    };

    Field.prototype.render = function() {
      this._empty();
      this._renderLabel();
      this._renderInput();
      if (this.options.required) {
        this._designateAsRequired();
      }
      this.reset();
      return this;
    };

    Field.prototype.renderErrors = function(messages) {
      return this.$el.addClass("error").append("<span class=\"inline-errors\">" + (messages.join(", ")) + "</span>");
    };

    Field.prototype.disable = function() {
      return this._input().attr("disabled", "disabled");
    };

    Field.prototype.enable = function() {
      return this._input().removeAttr("disabled");
    };

    Field.prototype.get = function() {
      return this._input().val();
    };

    Field.prototype.set = function(val) {
      return this._input().val(val);
    };

    Field.prototype.clear = function() {
      this._input().val("");
      return this.clearErrors();
    };

    Field.prototype.clearErrors = function() {
      this.$el.removeClass("error");
      return this.$(".inline-errors").remove();
    };

    Field.prototype.rerenderErrors = function(messages) {
      this.clearErrors();
      return this.renderErrors(messages);
    };

    Field.prototype.reset = function() {
      return this.set(this.model.get(this.options.attribute));
    };

    Field.prototype.commit = function() {
      return this.model.set(this.options.attribute, this.get());
    };

    Field.prototype.applyAutoCommit = function() {
      if (this.options.autoCommit) {
        return this.commit();
      }
    };

    Field.prototype._input = function() {
      return this.input || (this.input = this.$("input"));
    };

    Field.prototype._empty = function() {
      this.$el.empty();
      return this.input = null;
    };

    Field.prototype._renderLabel = function() {
      return this.$el.append(this.labelTemplate({
        id: this.cid,
        options: this.options
      }));
    };

    Field.prototype._renderInput = function() {
      return this.$el.append(this.inputTemplate({
        id: this.cid,
        options: this.options
      }));
    };

    Field.prototype._designateAsRequired = function() {
      return this.$el.addClass("required");
    };

    Field.prototype._defaults = function() {
      return {
        placeholder: this.options.label,
        autoCommit: true,
        required: false
      };
    };

    return Field;

  })(Backbone.View);

}).call(this);
