// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Traction.Forms.TextArea = (function(superClass) {
    extend(TextArea, superClass);

    function TextArea() {
      return TextArea.__super__.constructor.apply(this, arguments);
    }

    TextArea.prototype.inputTemplate = _.template("<textarea id=\"<%= options.id %>\" name=\"<%= options.name %>\" placeholder=\"<%= options.placeholder %>\"/>");

    TextArea.prototype.events = {
      "change textarea": "applyAutoCommit"
    };

    TextArea.prototype._input = function() {
      return this.input || (this.input = this.$("textarea"));
    };

    return TextArea;

  })(Traction.Forms.Field);

}).call(this);
