// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Traction.Forms.TextArea = (function(_super) {
    __extends(TextArea, _super);

    function TextArea() {
      _ref = TextArea.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    TextArea.prototype.inputTemplate = _.template("<textarea id=\"<%= options.id %>\" name=\"<%= options.name %>\" placeholder=\"<%= options.placeholder %>\"/>");

    TextArea.prototype.events = {
      "change textarea": "applyAutoCommit"
    };

    TextArea.prototype._input = function() {
      return this.input || (this.input = this.$("textarea"));
    };

    return TextArea;

  })(Traction.Forms.Field);

}).call(this);
