// Generated by CoffeeScript 1.8.0
(function() {
  jasmine.SharedExamples = {};

  JST = {};

  jasmine.itShouldBehaveLike = function(sharedExampleGroupName, options) {
    var sharedExampleGroup;
    if (sharedExampleGroup = jasmine.SharedExamples[sharedExampleGroupName]) {
      return sharedExampleGroup(options);
    } else {
      throw "Can't find shared example group '" + sharedExampleGroupName;
    }
  };

  jasmine.sharedExamplesFor = function(sharedExampleGroupName, examples) {
    return jasmine.SharedExamples[sharedExampleGroupName] = examples;
  };

  jasmine.Matchers.prototype.toBeInstanceOf = function(expected) {
    return this.actual instanceof expected;
  };

}).call(this);
