// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  describe("Rails collection", function() {
    return describe("#build", function() {
      var TestCollection, TestModel;
      TestModel = (function(_super) {
        __extends(TestModel, _super);

        function TestModel() {
          return TestModel.__super__.constructor.apply(this, arguments);
        }

        return TestModel;

      })(Backbone.Model);
      TestCollection = (function(_super) {
        __extends(TestCollection, _super);

        function TestCollection() {
          return TestCollection.__super__.constructor.apply(this, arguments);
        }

        TestCollection.prototype.model = TestModel;

        return TestCollection;

      })(Traction.Rails.Collection);
      beforeEach(function() {
        return this.collection = new TestCollection();
      });
      it("returns an instance of the collection's model", function() {
        return expect(this.collection.build()).toBeInstanceOf(TestModel);
      });
      it("does not add the model to the collection", function() {
        this.collection.build();
        return expect(this.collection.length).toBe(0);
      });
      return it("assigns the urlRoot property", function() {
        this.collection.url = "/index";
        return expect(this.collection.build().urlRoot).toBe("/index");
      });
    });
  });

}).call(this);
