// Generated by CoffeeScript 1.6.3
(function() {
  describe("Traction.Forms.TextField", function() {
    var createInstance;
    createInstance = function(options) {
      var defaults;
      defaults = {
        attribute: "first_name",
        name: "first_name_input",
        label: "First name",
        model: new Backbone.Model()
      };
      return new Traction.Forms.TextField(_.extend(defaults, options));
    };
    describe("shared behavior", function() {
      jasmine.itShouldBehaveLike("a field", {
        createInstance: createInstance,
        input: "input"
      });
      return jasmine.itShouldBehaveLike("a text field", {
        createInstance: createInstance,
        input: "input"
      });
    });
    return describe("#render", function() {
      return it("renders an input with the correct type", function() {
        var field;
        field = createInstance().render();
        return expect(field.$("input").attr("type")).toBe("text");
      });
    });
  });

}).call(this);
