// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Traction.Rendering.AppendStrategy = (function(_super) {

    __extends(AppendStrategy, _super);

    function AppendStrategy() {
      return AppendStrategy.__super__.constructor.apply(this, arguments);
    }

    AppendStrategy.prototype.initialize = function() {
      return this.setElement(this.options.renderWithin);
    };

    AppendStrategy.prototype.render = function() {
      return this.$el.empty();
    };

    AppendStrategy.prototype.outlet = function(children) {
      return this.$el.append(children.els());
    };

    return AppendStrategy;

  })(Backbone.View);

}).call(this);
