// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Traction.Rendering.AppendStrategy = (function(_super) {
    __extends(AppendStrategy, _super);

    function AppendStrategy() {
      return AppendStrategy.__super__.constructor.apply(this, arguments);
    }

    AppendStrategy.prototype.initialize = function(options) {
      return this.setElement(options.renderWithin);
    };

    AppendStrategy.prototype.call = function(options) {
      if (options == null) {
        options = {};
      }
      this.$el.empty();
      if (options.children != null) {
        return this.$el.append(options.children.els());
      }
    };

    return AppendStrategy;

  })(Backbone.View);

}).call(this);
