// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Traction.Rendering.AppendStrategy = (function(superClass) {
    extend(AppendStrategy, superClass);

    function AppendStrategy() {
      return AppendStrategy.__super__.constructor.apply(this, arguments);
    }

    AppendStrategy.prototype.initialize = function() {
      return this.setElement(this.options.renderWithin);
    };

    AppendStrategy.prototype.call = function(options) {
      if (options == null) {
        options = {};
      }
      this.$el.empty();
      if (options.children != null) {
        return this.$el.append(options.children.els());
      }
    };

    return AppendStrategy;

  })(Backbone.View);

}).call(this);
