// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Traction.Rendering.PrerenderedStrategy = (function(superClass) {
    extend(PrerenderedStrategy, superClass);

    function PrerenderedStrategy(options) {
      this.setElement(options.renderWithin);
      PrerenderedStrategy.__super__.constructor.apply(this, arguments);
    }

    return PrerenderedStrategy;

  })(Traction.Rendering.NodeStrategy);

}).call(this);
