// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Traction.Rendering.TemplateStrategy = (function(_super) {
    __extends(TemplateStrategy, _super);

    TemplateStrategy.prototype.defaultTemplateFinder = function(name) {
      var path;
      path = "" + Traction.config.templatePath + "/" + name;
      return JST[path];
    };

    function TemplateStrategy(options) {
      this.setElement(options.renderWithin);
      this.template = this.findTemplate(options.template);
      TemplateStrategy.__super__.constructor.apply(this, arguments);
    }

    TemplateStrategy.prototype.findTemplate = function(name) {
      return (Traction.config.findTemplate || this.defaultTemplateFinder)(name) || (function() {
        throw "Missing template: " + name;
      })();
    };

    TemplateStrategy.prototype.call = function(options) {
      if (options == null) {
        options = {};
      }
      this.insert(this._template({
        context: options.bindTo
      }));
      return TemplateStrategy.__super__.call.call(this, options);
    };

    TemplateStrategy.prototype.buildOutlet = function(outletName) {
      outletName || (outletName = "");
      return "<script data-outlet='" + outletName + "'></script>";
    };

    TemplateStrategy.prototype.insert = function(content) {
      if (Traction.config.supportIE && Traction.IE.supportsInnerHTMLForTag(this.el.tagName)) {
        return this.$el.html(content);
      } else {
        return this.el.innerHTML = content;
      }
    };

    TemplateStrategy.prototype._template = function(options) {
      return this.template(_.extend(options || {}, this._defaultTemplateOptions()));
    };

    TemplateStrategy.prototype._defaultTemplateOptions = function() {
      return {
        outlet: this.buildOutlet
      };
    };

    return TemplateStrategy;

  })(Traction.Rendering.NodeStrategy);

}).call(this);
