// Generated by CoffeeScript 1.9.3
(function() {
  Traction.ComputedAttribute = (function() {
    function ComputedAttribute(attribute1, computation1) {
      this.attribute = attribute1;
      this.computation = computation1;
    }

    ComputedAttribute.prototype.bindTo = function(model) {
      var dependency, i, len, ref;
      this.model = model;
      ref = this._dependencies();
      for (i = 0, len = ref.length; i < len; i++) {
        dependency = ref[i];
        this.model.on("change:" + dependency, this._assign, this);
      }
      return this._assign();
    };

    ComputedAttribute.prototype._dependencies = function() {
      return _.map(this._getterCalls(), function(match) {
        return match.replace(/this\.get\("/, "").replace(/\W/g, "");
      });
    };

    ComputedAttribute.prototype._getterCalls = function() {
      return this.computation.toString().match(/this\.get\(.*?\)/g);
    };

    ComputedAttribute.prototype._assign = function() {
      return this.model.set(this.attribute, this.computation.apply(this.model));
    };

    return ComputedAttribute;

  })();

  Traction.ComputedAttributes = {
    _assignComputedAttributes: function() {
      var attribute, computation, ref, results;
      this.computedAttributes || (this.computedAttributes = {});
      ref = this.computedAttributes;
      results = [];
      for (attribute in ref) {
        computation = ref[attribute];
        results.push(new Traction.ComputedAttribute(attribute, computation).bindTo(this));
      }
      return results;
    }
  };

}).call(this);
