// Generated by CoffeeScript 1.8.0
(function() {
  window.Traction = {
    Rendering: {},
    Bindings: {},
    TemplateHelpers: {},
    Rails: {},
    Forms: {},
    config: {
      templatePath: "templates"
    }
  };

}).call(this);
