// Generated by CoffeeScript 1.8.0
(function() {
  Traction.Decorator = (function() {
    _.extend(Decorator.prototype, Traction.ComputedAttributes);

    function Decorator(decorated) {
      this.decorated = decorated;
      _.defaults(this, this.decorated);
      if (this._attributesComputable()) {
        this._assignComputedAttributes();
      }
    }

    Decorator.prototype._attributesComputable = function() {
      return this.on && this.get && this.set;
    };

    return Decorator;

  })();

  Traction.Decorator.extend = Backbone.Model.extend;

}).call(this);
