// Generated by CoffeeScript 1.9.3
(function() {
  Traction.IE = {
    supportsInnerHTMLForTag: function(tagName) {
      var ref;
      return (ref = tagName.toUpperCase()) === "COL" || ref === "COLGROUP" || ref === "FRAMESET" || ref === "HEAD" || ref === "HTML" || ref === "STYLE" || ref === "TABLE" || ref === "TBODY" || ref === "TFOOT" || ref === "THEAD" || ref === "TITLE" || ref === "TR";
    }
  };

}).call(this);
