// Generated by CoffeeScript 1.3.3
(function() {

  Traction.IE = {
    supportsInnerHTMLForTag: function(tagName) {
      var _ref;
      return (_ref = tagName.toUpperCase()) === "COL" || _ref === "COLGROUP" || _ref === "FRAMESET" || _ref === "HEAD" || _ref === "HTML" || _ref === "STYLE" || _ref === "TABLE" || _ref === "TBODY" || _ref === "TFOOT" || _ref === "THEAD" || _ref === "TITLE" || _ref === "TR";
    }
  };

}).call(this);
