// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Traction.Model = (function(_super) {
    __extends(Model, _super);

    _.extend(Model.prototype, Traction.ComputedAttributes);

    function Model() {
      Model.__super__.constructor.apply(this, arguments);
      this._assignComputedAttributes();
    }

    return Model;

  })(Backbone.Model);

}).call(this);
