// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Traction.Model = (function(superClass) {
    extend(Model, superClass);

    _.extend(Model.prototype, Traction.ComputedAttributes);

    function Model() {
      Model.__super__.constructor.apply(this, arguments);
      this._assignComputedAttributes();
    }

    return Model;

  })(Backbone.Model);

}).call(this);
