// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Traction.View = (function(_super) {

    __extends(View, _super);

    function View(options) {
      this.children = new Traction.ViewCollection();
      View.__super__.constructor.apply(this, arguments);
      this.renderer = this.buildRenderer();
    }

    View.prototype.buildRenderer = function() {
      if (this.template) {
        return new Traction.Rendering.TemplateStrategy({
          source: this.template,
          renderWithin: this.el
        });
      } else if (this.options.el) {
        return new Traction.Rendering.PrerenderedStrategy({
          renderWithin: this.el
        });
      } else {
        return new Traction.Rendering.AppendStrategy({
          renderWithin: this.el
        });
      }
    };

    View.prototype.proxyEvent = function(target, event, newEvent) {
      var callback,
        _this = this;
      callback = function() {
        var args;
        args = Array.prototype.slice.call(arguments);
        args.unshift(newEvent || event);
        return _this.trigger.apply(_this, args);
      };
      return this.listenTo(target, event, callback);
    };

    View.prototype.render = function() {
      this.renderer.render({
        binding: this.binding
      });
      this.renderer.outlet(this.children.render());
      return this;
    };

    return View;

  })(Backbone.View);

  Traction.View.extend = function(klass) {
    return _.extend(this.prototype, klass.prototype);
  };

}).call(this);
