// Generated by CoffeeScript 1.3.3
(function() {

  Traction.TemplateHelpers.Formatting = {
    downcase: function(string) {
      return string.toLowerCase();
    },
    upcase: function(string) {
      return string.toUpperCase();
    },
    append: function(string, append) {
      return string + append;
    },
    nonBreaking: function(string) {
      if (string) {
        return string.replace(/\s/g, "&nbsp;");
      } else {
        return "&nbsp;";
      }
    }
  };

}).call(this);
