// Generated by CoffeeScript 1.3.3
(function() {

  Traction.TemplateHelpers.Formatting = {
    downcase: function(string) {
      return string.toLowerCase();
    },
    upcase: function(string) {
      return string.toUpperCase();
    },
    append: function(string, append) {
      return string + append;
    },
    nonBreaking: function(string) {
      return string || "&nbsp;";
    }
  };

}).call(this);
